# This file was generated by the {rix} R package v0.6.0 on 2024-05-09
# with following call:
# >rix(r_ver = "ad7efee13e0d216bf29992311536fce1d3eefbef",
#  > r_pkgs = c("devtools",
#  > "lattice",
#  > "latticeExtra",
#  > "rmarkdown",
#  > "FITSio",
#  > "reshape2",
#  > "classInt",
#  > "imager",
#  > "fields",
#  > "latex2exp",
#  > "viridis",
#  > "rasterVis",
#  > "IDPmisc",
#  > "reticulate",
#  > "yaml",
#  > "gtools",
#  > "data.table",
#  > "spatstat",
#  > "colorspace",
#  > "ggplot2",
#  > "spam",
#  > "sp",
#  > "stringr",
#  > "rgl",
#  > "beepr",
#  > "codetools",
#  > "inlabru",
#  > "fmesher"),
#  > system_pkgs = c("glibc"),
#  > git_pkgs = list(package_name = "INLAutils",
#  > repo_url = "https://github.com/timcdlucas/INLAutils.git",
#  >      branch_name = "master",
#  > commit = "74d769a"),
#  > ide = "rstudio",
#  > project_path = path_to_project,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision ad7efee13e0d216bf29992311536fce1d3eefbef for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/ad7efee13e0d216bf29992311536fce1d3eefbef.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) devtools lattice latticeExtra rmarkdown FITSio reshape2 classInt imager fields latex2exp viridis rasterVis IDPmisc reticulate yaml gtools data_table spatstat colorspace ggplot2 spam sp stringr rgl beepr codetools inlabru fmesher target crew here;
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "INLAutils";
    src = pkgs.fetchgit {
      url = "https://github.com/timcdlucas/INLAutils.git";
      branchName = "master";
      rev = "74d769a";
      sha256 = "sha256-0F171f3wuYm83uCcJKBKIrtu2SrSEI29PEe7iZeTYes=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) assertthat raster RColorBrewer sp reshape2 tidyr cowplot ggplot2;
    };
  }) ];
  system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix gnugrep glibc python3;
};
 rstudio_pkgs = pkgs.rstudioWrapper.override {
  packages = [ git_archive_pkgs rpkgs ];
};
 python_pkgs = builtins.attrValues{
  inherit (pkgs.python311Packages) numpy pandas matplotlib astropy;
};
 in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs  system_packages rstudio_pkgs python_pkgs];
      
    QT_XCB_GL_INTEGRATION="none";
  }
